version: '3.8'

networks:
  common-net:
    driver: bridge

volumes:
  mysql-db-data:
    driver: local
  pgsql-db-data:
    driver: local

services:
  nginx-server:
    image: nginx:stable-alpine
    container_name: nginx-server-container
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/sites:/etc/nginx/conf.d
      - ./www/app-01:/var/www/app-01.test/httpdocs
      - ./www/app-02:/var/www/app-02.test/httpdocs
    depends_on:
      - php74
      - php82
    networks:
      common-net:
        aliases:
          - app-01.test
          - app-01b.test
          - app-02.test
  mysql-db:
    image: mysql:5.7.40
    container_name: mysql-db-container
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-db-data:/var/lib/mysql
    networks:
      - common-net
  pgsql-db:
    image: postgres:15.2
    container_name: pgsql-db-container
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - pgsql-db-data:/var/lib/postgresql/data
    networks:
      - common-net
  adminer:
    image: adminer:4.8.1
    container_name: adminer-container
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - common-net
  php74:
    build:
      context: ./php/php74
    container_name: php74-container
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - ./php/php74/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - common-net
  php82:
    build:
      context: ./php/php82
    container_name: php82-container
    restart: unless-stopped
    ports:
      - 9001:9000
    volumes:
      - ./www/app-01:/var/www/app-01.test/httpdocs
      - ./www/app-02:/var/www/app-02.test/httpdocs
      - ./php/php82/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - common-net
