version: '3.8'

networks:
  common-net:
    driver: bridge

volumes:
  central-db-data:
    driver: local

services:
  nginx-server:
    image: nginx:stable-alpine
    container_name: nginx-server-container
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/sites:/etc/nginx/conf.d
      - ./www/app-01:/var/www/app-01.test/httpdocs/
    networks:
      common-net:
        aliases:
          - app-01.test
  central-db:
    image: mysql:5.7.40
    container_name: central-db-container
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - central-db-data:/var/lib/mysql
    networks:
      - common-net
  app-01:
    build:
      context: ./php/app-01
    container_name: app-01-container
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./www/app-01:/var/www/app-01.test/httpdocs
      - ./php/app-01/custom.ini:/usr/local/etc/php/conf.d/app-01.ini
    networks:
      - common-net
